export const paths = {
  home: '/',
  auth: {
    login: '/auth/login',
    acceptInvitation: '/auth/accept-invitation',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    callback: '/auth/callback',
  },
  employee: {
    dashboard: '/dashboard',
    onboarding: '/onboarding',
    pending: '/pending',
    leave: '/leave',
    medical: '/medical',
    overtime: '/overtime',
    payslips: '/payslips',
    policies: '/policies',
    profile: '/profile',
  },
  admin: {
    dashboard: '/admin',
    onboarding: '/admin/onboarding',
    approvals: '/admin/approvals',
    employees: '/admin/employees',
    payroll: '/admin/payroll',
    policies: '/admin/policies',
    settings: '/admin/settings',
    profile: '/admin/profile',
  },
} as const;
